apiVersion: v1
kind: Service
metadata:
  name: {{ include "ghost-blog.fullname" . }}
  labels:
    {{- include "ghost-blog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 2368
      protocol: TCP
  selector:
    {{- include "ghost-blog.selectorLabels" . | nindent 4 }}
